[build]
  command = "pnpm build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  # 0G Mainnet
  NEXT_PUBLIC_OG_CHAIN_ID = "16661"
  NEXT_PUBLIC_OG_RPC_URL = "https://evmrpc.0g.ai"
  NEXT_PUBLIC_OG_EXPLORER_URL = "https://chainscan.0g.ai"
  NEXT_PUBLIC_OG_CHAIN_NAME = "0G Mainnet"
  NEXT_PUBLIC_OG_INDEXER_URL = "https://indexer-storage-turbo.0g.ai"
